package com.monitor.app.dataobject;

import java.util.Date;

public class DeviceAlarm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_device_alarm.alarm_id
     *
     * @mbggenerated
     */
    private Long alarmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_device_alarm.device_id
     *
     * @mbggenerated
     */
    private Long deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_device_alarm.alarm_name
     *
     * @mbggenerated
     */
    private String alarmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_device_alarm.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_device_alarm.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_device_alarm.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_device_alarm.alarm_id
     *
     * @return the value of cr_device_alarm.alarm_id
     *
     * @mbggenerated
     */
    public Long getAlarmId() {
        return alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_device_alarm.alarm_id
     *
     * @param alarmId the value for cr_device_alarm.alarm_id
     *
     * @mbggenerated
     */
    public void setAlarmId(Long alarmId) {
        this.alarmId = alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_device_alarm.device_id
     *
     * @return the value of cr_device_alarm.device_id
     *
     * @mbggenerated
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_device_alarm.device_id
     *
     * @param deviceId the value for cr_device_alarm.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_device_alarm.alarm_name
     *
     * @return the value of cr_device_alarm.alarm_name
     *
     * @mbggenerated
     */
    public String getAlarmName() {
        return alarmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_device_alarm.alarm_name
     *
     * @param alarmName the value for cr_device_alarm.alarm_name
     *
     * @mbggenerated
     */
    public void setAlarmName(String alarmName) {
        this.alarmName = alarmName == null ? null : alarmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_device_alarm.status
     *
     * @return the value of cr_device_alarm.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_device_alarm.status
     *
     * @param status the value for cr_device_alarm.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_device_alarm.gmt_create
     *
     * @return the value of cr_device_alarm.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_device_alarm.gmt_create
     *
     * @param gmtCreate the value for cr_device_alarm.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_device_alarm.gmt_modify
     *
     * @return the value of cr_device_alarm.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_device_alarm.gmt_modify
     *
     * @param gmtModify the value for cr_device_alarm.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}