package com.monitor.app.dataobject;

import java.util.Date;

public class DeviceAlarmDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_device_alarm_detail.alarm_id
     *
     * @mbggenerated
     */
    private Long alarmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_device_alarm_detail.var_id
     *
     * @mbggenerated
     */
    private Long varId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_device_alarm_detail.value
     *
     * @mbggenerated
     */
    private Long value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_device_alarm_detail.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_device_alarm_detail.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_device_alarm_detail.alarm_id
     *
     * @return the value of cr_device_alarm_detail.alarm_id
     *
     * @mbggenerated
     */
    public Long getAlarmId() {
        return alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_device_alarm_detail.alarm_id
     *
     * @param alarmId the value for cr_device_alarm_detail.alarm_id
     *
     * @mbggenerated
     */
    public void setAlarmId(Long alarmId) {
        this.alarmId = alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_device_alarm_detail.var_id
     *
     * @return the value of cr_device_alarm_detail.var_id
     *
     * @mbggenerated
     */
    public Long getVarId() {
        return varId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_device_alarm_detail.var_id
     *
     * @param varId the value for cr_device_alarm_detail.var_id
     *
     * @mbggenerated
     */
    public void setVarId(Long varId) {
        this.varId = varId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_device_alarm_detail.value
     *
     * @return the value of cr_device_alarm_detail.value
     *
     * @mbggenerated
     */
    public Long getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_device_alarm_detail.value
     *
     * @param value the value for cr_device_alarm_detail.value
     *
     * @mbggenerated
     */
    public void setValue(Long value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_device_alarm_detail.gmt_create
     *
     * @return the value of cr_device_alarm_detail.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_device_alarm_detail.gmt_create
     *
     * @param gmtCreate the value for cr_device_alarm_detail.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_device_alarm_detail.gmt_modify
     *
     * @return the value of cr_device_alarm_detail.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_device_alarm_detail.gmt_modify
     *
     * @param gmtModify the value for cr_device_alarm_detail.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}