package com.monitor.app.dataobject;

import java.util.Date;

public class ModelVar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var.var_id
     *
     * @mbggenerated
     */
    private Long varId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var.var_name
     *
     * @mbggenerated
     */
    private String varName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var.alias
     *
     * @mbggenerated
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var.model_id
     *
     * @mbggenerated
     */
    private Long modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var.var_id
     *
     * @return the value of cr_model_var.var_id
     *
     * @mbggenerated
     */
    public Long getVarId() {
        return varId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var.var_id
     *
     * @param varId the value for cr_model_var.var_id
     *
     * @mbggenerated
     */
    public void setVarId(Long varId) {
        this.varId = varId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var.var_name
     *
     * @return the value of cr_model_var.var_name
     *
     * @mbggenerated
     */
    public String getVarName() {
        return varName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var.var_name
     *
     * @param varName the value for cr_model_var.var_name
     *
     * @mbggenerated
     */
    public void setVarName(String varName) {
        this.varName = varName == null ? null : varName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var.alias
     *
     * @return the value of cr_model_var.alias
     *
     * @mbggenerated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var.alias
     *
     * @param alias the value for cr_model_var.alias
     *
     * @mbggenerated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var.type
     *
     * @return the value of cr_model_var.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var.type
     *
     * @param type the value for cr_model_var.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var.unit
     *
     * @return the value of cr_model_var.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var.unit
     *
     * @param unit the value for cr_model_var.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var.model_id
     *
     * @return the value of cr_model_var.model_id
     *
     * @mbggenerated
     */
    public Long getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var.model_id
     *
     * @param modelId the value for cr_model_var.model_id
     *
     * @mbggenerated
     */
    public void setModelId(Long modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var.gmt_create
     *
     * @return the value of cr_model_var.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var.gmt_create
     *
     * @param gmtCreate the value for cr_model_var.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var.gmt_modify
     *
     * @return the value of cr_model_var.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var.gmt_modify
     *
     * @param gmtModify the value for cr_model_var.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}