package com.monitor.app.dataobject;

import java.util.Date;

public class ModelVarValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var_value.var_id
     *
     * @mbggenerated
     */
    private Long varId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var_value.model_id
     *
     * @mbggenerated
     */
    private Long modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var_value.value
     *
     * @mbggenerated
     */
    private Integer value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var_value.alias
     *
     * @mbggenerated
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var_value.graph_id
     *
     * @mbggenerated
     */
    private Integer graphId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var_value.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_var_value.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var_value.var_id
     *
     * @return the value of cr_model_var_value.var_id
     *
     * @mbggenerated
     */
    public Long getVarId() {
        return varId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var_value.var_id
     *
     * @param varId the value for cr_model_var_value.var_id
     *
     * @mbggenerated
     */
    public void setVarId(Long varId) {
        this.varId = varId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var_value.model_id
     *
     * @return the value of cr_model_var_value.model_id
     *
     * @mbggenerated
     */
    public Long getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var_value.model_id
     *
     * @param modelId the value for cr_model_var_value.model_id
     *
     * @mbggenerated
     */
    public void setModelId(Long modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var_value.value
     *
     * @return the value of cr_model_var_value.value
     *
     * @mbggenerated
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var_value.value
     *
     * @param value the value for cr_model_var_value.value
     *
     * @mbggenerated
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var_value.alias
     *
     * @return the value of cr_model_var_value.alias
     *
     * @mbggenerated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var_value.alias
     *
     * @param alias the value for cr_model_var_value.alias
     *
     * @mbggenerated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var_value.graph_id
     *
     * @return the value of cr_model_var_value.graph_id
     *
     * @mbggenerated
     */
    public Integer getGraphId() {
        return graphId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var_value.graph_id
     *
     * @param graphId the value for cr_model_var_value.graph_id
     *
     * @mbggenerated
     */
    public void setGraphId(Integer graphId) {
        this.graphId = graphId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var_value.gmt_create
     *
     * @return the value of cr_model_var_value.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var_value.gmt_create
     *
     * @param gmtCreate the value for cr_model_var_value.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_var_value.gmt_modify
     *
     * @return the value of cr_model_var_value.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_var_value.gmt_modify
     *
     * @param gmtModify the value for cr_model_var_value.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}