package com.monitor.app.dataobject;

import java.util.Date;

public class ModelAccessory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_accessory.accessory_id
     *
     * @mbggenerated
     */
    private Long accessoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_accessory.accessory_name
     *
     * @mbggenerated
     */
    private String accessoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_accessory.accessory_price
     *
     * @mbggenerated
     */
    private Long accessoryPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_accessory.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_accessory.file_path
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_accessory.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_model_accessory.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_accessory.accessory_id
     *
     * @return the value of cr_model_accessory.accessory_id
     *
     * @mbggenerated
     */
    public Long getAccessoryId() {
        return accessoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_accessory.accessory_id
     *
     * @param accessoryId the value for cr_model_accessory.accessory_id
     *
     * @mbggenerated
     */
    public void setAccessoryId(Long accessoryId) {
        this.accessoryId = accessoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_accessory.accessory_name
     *
     * @return the value of cr_model_accessory.accessory_name
     *
     * @mbggenerated
     */
    public String getAccessoryName() {
        return accessoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_accessory.accessory_name
     *
     * @param accessoryName the value for cr_model_accessory.accessory_name
     *
     * @mbggenerated
     */
    public void setAccessoryName(String accessoryName) {
        this.accessoryName = accessoryName == null ? null : accessoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_accessory.accessory_price
     *
     * @return the value of cr_model_accessory.accessory_price
     *
     * @mbggenerated
     */
    public Long getAccessoryPrice() {
        return accessoryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_accessory.accessory_price
     *
     * @param accessoryPrice the value for cr_model_accessory.accessory_price
     *
     * @mbggenerated
     */
    public void setAccessoryPrice(Long accessoryPrice) {
        this.accessoryPrice = accessoryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_accessory.file_name
     *
     * @return the value of cr_model_accessory.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_accessory.file_name
     *
     * @param fileName the value for cr_model_accessory.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_accessory.file_path
     *
     * @return the value of cr_model_accessory.file_path
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_accessory.file_path
     *
     * @param filePath the value for cr_model_accessory.file_path
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_accessory.gmt_create
     *
     * @return the value of cr_model_accessory.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_accessory.gmt_create
     *
     * @param gmtCreate the value for cr_model_accessory.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_model_accessory.gmt_modify
     *
     * @return the value of cr_model_accessory.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_model_accessory.gmt_modify
     *
     * @param gmtModify the value for cr_model_accessory.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}