package com.monitor.app.dataobject;

import java.util.Date;

public class plcModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_plc_model.model_id
     *
     * @mbggenerated
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_plc_model.model_name
     *
     * @mbggenerated
     */
    private String modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_plc_model.sensor_type
     *
     * @mbggenerated
     */
    private Integer sensorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_plc_model.io_type
     *
     * @mbggenerated
     */
    private Integer ioType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_plc_model.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_plc_model.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_plc_model.model_id
     *
     * @return the value of cr_plc_model.model_id
     *
     * @mbggenerated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_plc_model.model_id
     *
     * @param modelId the value for cr_plc_model.model_id
     *
     * @mbggenerated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_plc_model.model_name
     *
     * @return the value of cr_plc_model.model_name
     *
     * @mbggenerated
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_plc_model.model_name
     *
     * @param modelName the value for cr_plc_model.model_name
     *
     * @mbggenerated
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_plc_model.sensor_type
     *
     * @return the value of cr_plc_model.sensor_type
     *
     * @mbggenerated
     */
    public Integer getSensorType() {
        return sensorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_plc_model.sensor_type
     *
     * @param sensorType the value for cr_plc_model.sensor_type
     *
     * @mbggenerated
     */
    public void setSensorType(Integer sensorType) {
        this.sensorType = sensorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_plc_model.io_type
     *
     * @return the value of cr_plc_model.io_type
     *
     * @mbggenerated
     */
    public Integer getIoType() {
        return ioType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_plc_model.io_type
     *
     * @param ioType the value for cr_plc_model.io_type
     *
     * @mbggenerated
     */
    public void setIoType(Integer ioType) {
        this.ioType = ioType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_plc_model.gmt_create
     *
     * @return the value of cr_plc_model.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_plc_model.gmt_create
     *
     * @param gmtCreate the value for cr_plc_model.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_plc_model.gmt_modify
     *
     * @return the value of cr_plc_model.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_plc_model.gmt_modify
     *
     * @param gmtModify the value for cr_plc_model.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}