package com.monitor.app.dataobject;

import java.util.Date;

public class SiteStyle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_site_style.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_site_style.main_title
     *
     * @mbggenerated
     */
    private String mainTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_site_style.main_pic_name
     *
     * @mbggenerated
     */
    private String mainPicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_site_style.main_pic_path
     *
     * @mbggenerated
     */
    private String mainPicPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_site_style.banner_pic_name
     *
     * @mbggenerated
     */
    private String bannerPicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_site_style.banner_pic_path
     *
     * @mbggenerated
     */
    private String bannerPicPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_site_style.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_site_style.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_site_style.customer_id
     *
     * @return the value of cr_site_style.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_site_style.customer_id
     *
     * @param customerId the value for cr_site_style.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_site_style.main_title
     *
     * @return the value of cr_site_style.main_title
     *
     * @mbggenerated
     */
    public String getMainTitle() {
        return mainTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_site_style.main_title
     *
     * @param mainTitle the value for cr_site_style.main_title
     *
     * @mbggenerated
     */
    public void setMainTitle(String mainTitle) {
        this.mainTitle = mainTitle == null ? null : mainTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_site_style.main_pic_name
     *
     * @return the value of cr_site_style.main_pic_name
     *
     * @mbggenerated
     */
    public String getMainPicName() {
        return mainPicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_site_style.main_pic_name
     *
     * @param mainPicName the value for cr_site_style.main_pic_name
     *
     * @mbggenerated
     */
    public void setMainPicName(String mainPicName) {
        this.mainPicName = mainPicName == null ? null : mainPicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_site_style.main_pic_path
     *
     * @return the value of cr_site_style.main_pic_path
     *
     * @mbggenerated
     */
    public String getMainPicPath() {
        return mainPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_site_style.main_pic_path
     *
     * @param mainPicPath the value for cr_site_style.main_pic_path
     *
     * @mbggenerated
     */
    public void setMainPicPath(String mainPicPath) {
        this.mainPicPath = mainPicPath == null ? null : mainPicPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_site_style.banner_pic_name
     *
     * @return the value of cr_site_style.banner_pic_name
     *
     * @mbggenerated
     */
    public String getBannerPicName() {
        return bannerPicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_site_style.banner_pic_name
     *
     * @param bannerPicName the value for cr_site_style.banner_pic_name
     *
     * @mbggenerated
     */
    public void setBannerPicName(String bannerPicName) {
        this.bannerPicName = bannerPicName == null ? null : bannerPicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_site_style.banner_pic_path
     *
     * @return the value of cr_site_style.banner_pic_path
     *
     * @mbggenerated
     */
    public String getBannerPicPath() {
        return bannerPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_site_style.banner_pic_path
     *
     * @param bannerPicPath the value for cr_site_style.banner_pic_path
     *
     * @mbggenerated
     */
    public void setBannerPicPath(String bannerPicPath) {
        this.bannerPicPath = bannerPicPath == null ? null : bannerPicPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_site_style.gmt_create
     *
     * @return the value of cr_site_style.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_site_style.gmt_create
     *
     * @param gmtCreate the value for cr_site_style.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_site_style.gmt_modify
     *
     * @return the value of cr_site_style.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_site_style.gmt_modify
     *
     * @param gmtModify the value for cr_site_style.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}