package com.monitor.app.dataobject;

import java.util.Date;

public class UserSiteRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_user_site_relation.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_user_site_relation.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_user_site_relation.site_id
     *
     * @mbggenerated
     */
    private Long siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_user_site_relation.site_name
     *
     * @mbggenerated
     */
    private String siteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_user_site_relation.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_user_site_relation.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_user_site_relation.id
     *
     * @return the value of cr_user_site_relation.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_user_site_relation.id
     *
     * @param id the value for cr_user_site_relation.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_user_site_relation.user_id
     *
     * @return the value of cr_user_site_relation.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_user_site_relation.user_id
     *
     * @param userId the value for cr_user_site_relation.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_user_site_relation.site_id
     *
     * @return the value of cr_user_site_relation.site_id
     *
     * @mbggenerated
     */
    public Long getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_user_site_relation.site_id
     *
     * @param siteId the value for cr_user_site_relation.site_id
     *
     * @mbggenerated
     */
    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_user_site_relation.site_name
     *
     * @return the value of cr_user_site_relation.site_name
     *
     * @mbggenerated
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_user_site_relation.site_name
     *
     * @param siteName the value for cr_user_site_relation.site_name
     *
     * @mbggenerated
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName == null ? null : siteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_user_site_relation.gmt_create
     *
     * @return the value of cr_user_site_relation.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_user_site_relation.gmt_create
     *
     * @param gmtCreate the value for cr_user_site_relation.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_user_site_relation.gmt_modify
     *
     * @return the value of cr_user_site_relation.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_user_site_relation.gmt_modify
     *
     * @param gmtModify the value for cr_user_site_relation.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}